### ISSUE TITLE
Production doesn't start

### ISSUE THREAD

**Issue by haf** [webpack/react-starter#54]
> react-starter@0.0.0 start /Users/henrik.feldt/dev/react-starter
> node lib/server-production

module.js:338
    throw err;
          ^
Error: Cannot find module '../build/prerender/main.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/Users/henrik.feldt/dev/react-starter/lib/server.js:11:3)
    at Object.<anonymous> (/Users/henrik.feldt/dev/react-starter/lib/server-production.js:1:82)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! react-starter@0.0.0 start: `node lib/server-production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-starter@0.0.0 start script 'node lib/server-production'.
npm ERR! This is most likely a problem with the react-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/server-production
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/henrik.feldt/dev/react-starter/npm-debug.log

**Comment by haf** [comment]
It does, but `npm build` isn't the right command to run; run `npm run build` instead and it'll work.
