### ISSUE TITLE
problem run dev server as per README

### ISSUE THREAD

**Issue by eloop** [webpack/react-starter#59]
After npm installing I "npm run devserver" and get the following error. Must be something silly but I get the same thing if I do it in vagrant using the provided Vagrantfile.

$ ./node_modules/.bin/webpack-dev-server --config webpack-dev-server.config.js --progress --colors --port 2992 --inline
module.js:338
    throw err;
    ^
Error: Cannot find module 'webpack-dev-server.config.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/Volumes/DREWSDATA/tmp/react-starter/node_modules/webpack/bin/convert-argv.js:56:12)
    at Object.<anonymous> (/Volumes/DREWSDATA/tmp/react-starter/node_modules/webpack-dev-server/bin/webpack-dev-server.js:46:48)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
:( drw900@eloop:~/tmp/react-starter(master)
$ ls
README.md                        config                           npm-debug.log                    webpack-dev-server.config.js
Vagrantfile                      lib                              npm_global_packages.txt          webpack-hot-dev-server.config.js
app                              make-webpack-config.js           package.json                     webpack-production.config.js
build                            node_modules                     public                           webpack.config.js
:) drw900@eloop:~/tmp/react-starter(master)

**Comment by sokra** [comment]
fixed

**Comment by filmackay** [comment]
What was the fix? Can't see what could fix it in the relevant wip commit?

**Comment by sokra** [comment]
https://github.com/webpack/webpack/commit/9a800d5979e55b321883441736459e891d06bd8a
