### ISSUE TITLE
Fresh clone of this repo fails to build and run

### ISSUE THREAD

**Issue by broberson** [webpack/react-starter#74]
Following the instructions in the [README](https://github.com/webpack/react-starter/blob/master/README.md#local-installation), I cloned the repo to a new folder, ran `npm install`
in it, and tried to build and run the server. I doubt it's relevant, but I'm running Mac OS X 10.10.3. I get the same results using [Vagrant](https://github.com/webpack/react-starter/blob/master/README.md#installation-via-vagrant), only the paths are different.

    > npm run dev-server

    > react-starter@0.0.0 dev-server /Users/broberson/Projects/react-starter
    > webpack-dev-server --config webpack-dev-server.config.js --progress --colors --port 2992 --inline

    module.js:333
        throw err;
        ^
    Error: Cannot find module './app/routeHandlers/async'
        at Function.Module._resolveFilename (module.js:331:15)
        at Function.Module._load (module.js:273:25)
        at Module.require (module.js:357:17)
        at require (module.js:373:17)
        at module.exports (/Users/broberson/Projects/react-starter/make-webpack-config.js:95:9)
        at Object.<anonymous> (/Users/broberson/Projects/react-starter/webpack-dev-server.config.js:1:112)
        at Module._compile (module.js:449:26)
        at Object.Module._extensions..js (module.js:467:10)
        at Module.load (module.js:349:32)
        at Function.Module._load (module.js:305:12)
        at Module.require (module.js:357:17)
        at require (module.js:373:17)

    > node --version
    v0.11.13

    > npm --version
    2.5.0

Seems very similar to #59 from last month, which has been resolved.

**Comment by sokra** [comment]
yep, thanks

**Comment by broberson** [comment]
`npm run start-dev` seems to work now, in as far as it emits a bunch of webpack output. The next step, `npm run start-dev` fails on line 19 in lib/server.js, trying to make a new instance of Renderer, which was supposed to be loaded from a file in the build directory which is empty except for a stats.json file.

Maybe the instructions in README are outdated? I'm kind of puzzled.

**Comment by mattybow** [comment]
I think it's because `SimpleRenderer.js` needs `module.exports = SimpleRenderer;`  works when I edit that.

**Comment by sokra** [comment]
yup... changed this.

**Comment by sokra** [comment]
start the webpack-dev-server
> npm run dev-server

**wait for the first compilation is successful**

in another terminal/console
start the node.js server in development mode
> npm run start-dev

open this url in your browser
> http://localhost:8080/
