### ISSUE TITLE
vagrant installation method issues

### ISSUE THREAD

**Issue by thenewguy** [webpack/react-starter#98]
I may just be doing something wrong, but the vagrant installation doesn't seem to work for me and I am having a difficult time figuring it out.

Should 

```
vagrant up
vagrant ssh
cd /vagrant
```

just work with master?

Can anyone confirm it works for them with a Windows host using VirtualBox?  I get various npm errors during the build.

**Comment by thenewguy** [comment]
So I found an article on the internet that indicated the issue might be pathname lengths imposed by the Windows host.  Ref http://perrymitchell.net/article/npm-symlinks-through-vagrant-windows/

I have gotten a little farther using a symlink to a directory on the box filesystem.  Now everything installed.  Just can't get it to run yet.  For some reason `npm run dev-server` can't find express even though it is installed and visible under `/vagrant/node_modules/express`. `/vagrant/node_modules/` is symlinked to `/var/opt/node_modules/vagrant`

**Comment by thenewguy** [comment]
Oddly enough:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ ls $(npm root)
async                        file-loader         react-router
babel-core                   html-loader         stats-webpack-plugin
babel-eslint                 items-store         style-loader
babel-loader                 less                superagent
body-parser                  less-loader         url-loader
css-loader                   markdown-loader     uuid
eslint                       null-loader         webpack
eslint-plugin-react          react               webpack-dev-server
express                      react-hot-loader
extract-text-webpack-plugin  react-proxy-loader
vagrant@vagrant-ubuntu-trusty-64:/vagrant$
```

But no joy:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ sudo npm run dev-server

> react-starter@0.0.0 dev-server /vagrant
> webpack-dev-server --config webpack-dev-server.config.js --progress --colors -
-port 2992 --inline

module.js:338
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/opt/node_modules/vagrant/webpack-dev-server/lib/
Server.js:4:15)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "run" "dev-server"
npm ERR! node v2.5.0
npm ERR! npm  v2.13.2
npm ERR! code ELIFECYCLE
npm ERR! react-starter@0.0.0 dev-server: `webpack-dev-server --config webpack-de
v-server.config.js --progress --colors --port 2992 --inline`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-starter@0.0.0 dev-server script 'webpack-dev-server
 --config webpack-dev-server.config.js --progress --colors --port 2992 --inline'
.
npm ERR! This is most likely a problem with the react-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --config webpack-dev-server.config.js --progress
 --colors --port 2992 --inline
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-starter
npm ERR! There is likely additional logging output above.
npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "run" "dev-server"
npm ERR! node v2.5.0
npm ERR! npm  v2.13.2
npm ERR! path npm-debug.log.c52d3a8b9fc3c997429a67e0c8a75067
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.c52d3a8b9fc3c997429a6
7e0c8a75067' -> 'npm-debug.log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log
vagrant@vagrant-ubuntu-trusty-64:/vagrant$
```

**Comment by thenewguy** [comment]
I realized after posting that I was using an older version of npm, but it still happens with the latest version:
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ npm run express
npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "run" "express"
npm ERR! node v1.8.4
npm ERR! npm  v2.14.3

npm ERR! missing script: express
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "run" "express"
npm ERR! node v1.8.4
npm ERR! npm  v2.14.3
npm ERR! path npm-debug.log.05faba6fb116c3f76281b963b14b0329
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.05faba6fb116c3f76281b
963b14b0329' -> 'npm-debug.log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log
vagrant@vagrant-ubuntu-trusty-64:/vagrant$
```

**Comment by thenewguy** [comment]
I updated my previous comment.  I had copied the wrong command to generate the error output for the comment

**Comment by thenewguy** [comment]
Because of the previous botched comment I thought it would be prudent to show that the environment is otherwise in working condition so I copied the files off the shared folder for demonstration:
```
vagrant@vagrant-ubuntu-trusty-64:~$ sudo mkdir /vagrant2
vagrant@vagrant-ubuntu-trusty-64:~$ sudo chown vagrant:vagrant /vagrant2
vagrant@vagrant-ubuntu-trusty-64:~$ cd /vagrant2
vagrant@vagrant-ubuntu-trusty-64:/vagrant2$ cp -R /vagrant/* .
vagrant@vagrant-ubuntu-trusty-64:/vagrant2$ rm node_modules
vagrant@vagrant-ubuntu-trusty-64:/vagrant2$ ls
app     make-webpack-config.js  README.md    webpack.config.js
build   NOTES                   vagrant.bat  webpack-dev-server.config.js
config  package.json            vagrant-bin  webpack-hot-dev-server.config.js
lib     public                  Vagrantfile  webpack-production.config.js
vagrant@vagrant-ubuntu-trusty-64:/vagrant2$ npm install
...
unremarkable output
...
vagrant@vagrant-ubuntu-trusty-64:/vagrant2$ npm run dev-server
> webpack-dev-server --config webpack-dev-server.config.js --progress --colors -
-port 2992 --inline

 70% 1/1 build moduleshttp://localhost:2992/
webpack result is served from http://localhost:2992/_assets/
content is served from /vagrant2
Hash: a77e19084dfc55285b36
Version: webpack 1.12.1
Time: 20087ms
  Asset     Size  Chunks             Chunk Names
main.js   1.3 MB       0  [emitted]  main
   1.js  4.67 kB       1  [emitted]
   2.js  15.2 kB       2  [emitted]
...
snip
...
  [280] ./README.md 7.21 kB {2} [built]
webpack: bundle is now VALID.
♥
vagrant@vagrant-ubuntu-trusty-64:/vagrant2$
```

**Comment by thenewguy** [comment]
For reference, I demonstrate the environment works when copied off of the shared folder so that symlinked node_modules isn't required https://github.com/npm/npm/issues/7308#issuecomment-139841335

**Comment by thenewguy** [comment]
I've worked out the issues.  I am going to follow up with a pull request to make windows usage seamless out of the box
